spring:
  application:
    name: kafka_producer
  kafka:
    bootstrap-servers: localhost:9092
app:
  kafka:
    kafkaMessageTopic: "message-topic1"
    kafkaMessageGroupId: "kafka-message-group-id1"
